@URL=http://localhost/todo/backend

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWNhMUBnbWFpbC5jb20ifQ.zeY6Rm--spAS-DdrA6boEDxJVLErMyVoFj5KbwkZ7kg

### Create a User
POST {{URL}}/todo/create.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "title": "Title ToDo",
    "description": "Description ToDo",
    "deadline": "2022-12-08 14:34:05",
    "status": "A",
    "fk_user": "2"
}

### Atualizar um todo
POST {{URL}}/todo/update.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "id": 2,
    "title": "Title ToDo versão 2",
    "description": "Description ToDo",
    "deadline": "2022-12-08 14:34:05",
    "status": "A"
}

### Obter todos os todos
POST {{URL}}/todo/list.php
Authorization: {{JWT}}


### Obter todo pelo id
POST {{URL}}/todo/list.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "id": "2"
}

### Deletar um todo
POST {{URL}}/todo/delete.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "id": "6"
}