@URL=http://localhost/todo/backend

@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWNhMUBnbWFpbC5jb20ifQ.zeY6Rm--spAS-DdrA6boEDxJVLErMyVoFj5KbwkZ7kg

### Create a User
POST {{URL}}/user/create.php
Content-Type: application/json

{
    "name": "Juca da Silva",
    "email": "juca4@gmail.com",
    "password": "1234"
}

### Login (Generate Token)
POST {{URL}}/user/login.php
Content-Type: application/json

{
    "email": "juca4@gmail.com",
    "password": "1234"
}

### Valid Token
POST {{URL}}/auth/recursoqualquer.php
Authorization: {{JWT}}

### Atualizar um usuário
POST {{URL}}/user/update.php
Content-Type: application/json
Authorization: {{JWT}}

{
    "name": "Juca da Silva",
    "email": "juca1@gmail.com",
    "password": "juquinha1"
}

### Obter um usuário pelo EMAIL
POST {{URL}}/user/list.php
Authorization: {{JWT}}


### Deletar um usuário
POST {{URL}}/user/delete.php
Authorization: {{JWT}}
